# Generated by Django 2.2.5 on 2019-12-17 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseModel',
            new_name='Course',
        ),
    ]
