# Generated by Django 2.2.5 on 2019-12-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20191217_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
